### PR TITLE
3 members need to review in order to move the code to master branch

### PR DESCRIPTION
**Pull request by LoganBSanders**
This is for the dummy code, will be deleted

### CODE REVIEW

**Review by AselAkun — COMMENTED** [review]
very well

**Review by Saidshah1991 — APPROVED** [review]
its look good

**Review by AselAkun — APPROVED** [review]

**Review by Altynai-Bai — APPROVED** [review]
it is good

**Review by Altynai-Bai — APPROVED** [review]
great

**Pull request merged**
